# Use a lightweight OpenJDK base image
FROM openjdk:17-jdk-slim
# Set the working directory inside the container
WORKDIR /app

# Copy the application's jar file into the container
# The name must match the one generated by Maven
COPY target/task-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your Spring Boot application runs on
EXPOSE 8080

# Define environment variables for MongoDB connection
# These will be overridden by Kubernetes manifests later
ENV SPRING_DATA_MONGODB_URI="mongodb+srv://chandanboyina_db_user:9CVMNLOj13T2v2Mp@cluster0.cu8stoe.mongodb.net/task?retryWrites=true&w=majority&appName=Cluster0"

# Command to run the application when the container starts
CMD ["java", "-jar", "app.jar"]