# .github/workflows/backend-ci.yml
name: Java Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Code Build Step (CI)
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven (Code Build)
        run: mvn -B clean package -DskipTests # -DskipTests skips tests for faster build
        # This step ensures the application code compiles and the JAR file is created.

      # 2. Docker Build & Push Step (CD)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # Authentication uses GitHub Secrets, which you must set up.

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: chandanboyina/kaiburr-app:latest
          # This step builds the image using your Dockerfile and pushes it to Docker Hub.